name: Android CI/CD

on:
  push:
    branches:
      - v4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20  # Use latest LTS version

      - name: Install dependencies
        run: npm i        

      # - name: Delete Branch
      #   run: |
      #     git push origin --delete test_checkout_branch
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      # - name: Create and switch to new branch
      #   run: |
      #     git checkout -b test_checkout_branch
      #     git push origin test_checkout_branch
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          

      # - name: Use commit message
      #   run: |
      #     echo "Last commit message: ${{ steps.last_commit.outputs.message }}"   

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug  

      - name: Install Tree
        run: sudo apt-get install tree

      - name: Print Folder Structure
        run: tree -d

      # - name: Upload to Firebase App Distribution
      #   uses: w9jds/firebase-action@master
      #   with:
      #     args: appdistribution:distribute ./app/build/outputs/apk/debug/app-debug.apk --app 1:481720887348:android:dc082c38bf6312ac774261 --groups sampleAppTesters 
      ## <remove this as its a test to add release notes > --release-notes ${{ steps.last_commit.outputs.message }}
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
